### ISSUE TITLE
Other webapps that do similar things found and checked out

### ISSUE THREAD

**Issue by nielsbom** [FCCAmsterdam/tps3000#2]
Let's see if we can copysteal some of their features.

Please list the apps that were found and a short description of the relevant features.

**Comment by sepuckett86** [comment]
https://docs.google.com/document/d/14sI7ojvBOvhk7yksx5VC7uQW2dLX2x1PmAZpuRYmXDs/edit?usp=sharing

**Comment by nielsbom** [comment]
Cool, let's close this one then, Susan did the research.
